[project]
name = "demo-youtube-content-creation-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-generativeai>=0.8.6",
    "mcp[cli]>=2.2.0",
    "moviepy>=2.2.1",
    "pip>=26.2.1",
    "python-dotenv>=1.2.3",
    "streamlit>=1.64.0",
    "tavily-python>=0.8.4",
]
